### word2vec vs GloVe

In [1]:
import torch
import torch.nn as nn

from torchnlp.word_to_vector import GloVe

In [2]:
word_to_ix={"hello":0, "world":1}

lookup_tensor=torch.tensor([word_to_ix["world"]], dtype=torch.long)
print(lookup_tensor)

embeds=nn.Embedding(2, 5)
for p in embeds.parameters():
    print(p)
print(embeds)
world_embed=embeds(lookup_tensor)
print(world_embed)
lookup_tensor=torch.tensor([0,1], dtype=torch.long)
world_embed=embeds(lookup_tensor)
print(world_embed)

tensor([1])
Parameter containing:
tensor([[ 0.0871, -2.0126,  1.0752, -1.3317, -0.3909],
        [-0.2993, -0.6766,  1.6747, -0.6212,  0.6917]], requires_grad=True)
Embedding(2, 5)
tensor([[-0.2993, -0.6766,  1.6747, -0.6212,  0.6917]],
       grad_fn=<EmbeddingBackward>)
tensor([[ 0.0871, -2.0126,  1.0752, -1.3317, -0.3909],
        [-0.2993, -0.6766,  1.6747, -0.6212,  0.6917]],
       grad_fn=<EmbeddingBackward>)


In [3]:
vectors=GloVe()
vectors['hello']
print(vectors['go'], vectors['pig'].shape, sep='\n')

tensor([ 1.3893e-01, -1.9056e-02, -3.3891e-01,  1.2151e-01,  3.6523e-01,
        -1.7391e-01, -2.6735e-02, -5.0335e-02,  2.4743e-01,  2.4531e+00,
        -4.2113e-01,  2.3632e-01,  2.0513e-01, -1.0937e-02, -1.1480e-01,
        -3.7648e-02, -1.3440e-01,  8.6124e-01, -3.5803e-01,  9.2525e-02,
         2.8075e-01,  1.3649e-01,  2.0819e-01,  6.0206e-02, -1.8229e-01,
         1.0172e-01, -1.3200e-01, -3.1598e-01,  2.2241e-01, -1.9076e-01,
        -1.0884e-02,  1.6988e-01,  8.0345e-03,  1.3337e-01,  1.7724e-01,
        -1.9162e-01,  3.3681e-01,  3.0186e-01,  6.1654e-02,  7.6906e-03,
        -5.4406e-01,  5.0142e-02, -4.3115e-02, -2.6241e-01,  4.7462e-02,
         3.3670e-01, -2.8649e-01, -2.7414e-01,  2.6776e-02, -6.5939e-02,
         1.1021e-01,  2.8869e-01,  4.6712e-01,  1.2063e-01,  3.3831e-01,
        -3.0427e-04, -1.2116e-01, -1.5900e-01, -1.0514e-01, -3.8560e-02,
        -6.2205e-02,  3.5631e-02, -1.7852e-01, -1.3308e-01,  2.6103e-01,
        -1.1082e-01, -2.7463e-01,  1.8556e-01,  4.5